import express from 'express';
import cookieParser from 'cookie-parser';
import morgan from 'morgan';
import helmet from 'helmet';
import { globalRateLimiter } from './middlewares/rateLimiter.middleware';
import { errorHandler } from './middlewares/error.middleware';
//import healthRoutes from './routes/health-appointment.routes';
import analyticsRoutes from './routes/dashboard.routes';
import reportRoutes from './routes/export.eoutes';

const app = express();
app.use(helmet());
app.use(morgan('dev'));
app.use(globalRateLimiter);
app.use(express.json());
app.use(cookieParser());
app.use('/api/reports-analytics/analytics', analyticsRoutes);
app.use('/api/reports-analytics/report', reportRoutes);
app.use(errorHandler);
export default app;
